node {
    tools {
              maven '3.6.3'
              jdk 'jdk8'
              }
                stage("clone repository") {
		                    git "https://github.com/"
            	}
                stage('--Test--'){
                        steps{ 
                             mvn clean package --projects api-common,feedback-api

                        }
                }	
                stage('--feedback-api--'){
                        steps{
                                sh '''image="#########:8080/feedback-api:build-${BUILD_NUMBER}"
                                      docker build -t ${image} /var/lib/jenkins/QA-Portal/qa-portal-services/feedback-api
                                      docker push ${image}
                                      ssh ##.##.##.##  << EOF
                                      docker service update --image ${image} feedback-api
                                      '''
                        }
                }
        }
}